name: Waka Readme Stats

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@v1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          LANG_COUNT: 5
          TIME_RANGE: last_7_days
